#!/bin/bash

if [[ ! -d "bin" ]]; then
    mkdir bin
fi

# Build examples (tests)
gcc examples/save.c -Wall -Iinclude -o bin/save
gcc examples/load.c -Wall -Iinclude -o bin/load

gcc examples/loadandsave.c -Wall -Iinclude -o bin/lns
